// Settings:
:toc: macro
:!toc-title:

// URLs:
:img-hoc: https://hitsofcode.com/github/rdavid/goredoer?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/goredoer?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:img-publish: https://github.com/rdavid/goredoer/actions/workflows/publish.yml/badge.svg
:img-releases: https://img.shields.io/github/v/release/rdavid/goredoer?color=blue&label=%20&logo=semver&logoColor=white&style=flat
:img-test: https://github.com/rdavid/goredoer/actions/workflows/test.yml/badge.svg
:url-actionlint: https://github.com/rhysd/actionlint
:url-alpine: https://github.com/rdavid/shellbase/blob/master/container/alpine/Containerfile
:url-containerfile: https://github.com/rdavid/goredoer/blob/master/Containerfile
:url-cv: http://cv.rabkin.co.il
:url-goredo: http://www.goredo.stargrave.org/INSTALL.html
:url-hadolint: https://github.com/hadolint/hadolint
:url-hoc: https://hitsofcode.com/view/github/rdavid/goredoer?branch=master
:url-license: https://github.com/rdavid/goredoer/blob/master/LICENSES/0BSD.txt
:url-publish: https://github.com/rdavid/goredoer/actions/workflows/publish.yml
:url-redo: http://cr.yp.to/redo.html
:url-releases: https://github.com/rdavid/goredoer/releases
:url-reuse: https://github.com/fsfe/reuse-tool
:url-shellbase: https://github.com/rdavid/shellbase
:url-shellcheck: https://github.com/koalaman/shellcheck
:url-shfmt: https://github.com/mvdan/sh
:url-test: https://github.com/rdavid/goredoer/actions/workflows/test.yml
:url-typos: https://github.com/crate-ci/typos
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint

= Goredoer

// The width is set to 79 characters, and the height is 11 lines. An ASCII art
// generator is used with the specific font Colossal:
//  http://patorjk.com/software/taag/#p=display&f=Colossal&t=+goredoer
[,sh]
----
                                                 888                           
                                                 888                           
                                                 888                           
           .d88b.   .d88b.  888d888 .d88b.   .d88888  .d88b.   .d88b.  888d888 
          d88P"88b d88""88b 888P"  d8P  Y8b d88" 888 d88""88b d8P  Y8b 888P"   
          888  888 888  888 888    88888888 888  888 888  888 88888888 888     
          Y88b 888 Y88..88P 888    Y8b.     Y88b 888 Y88..88P Y8b.     888     
           "Y88888  "Y88P"  888     "Y8888   "Y88888  "Y88P"   "Y8888  888     
               888                                                             
          Y8b d88P                                                             
           "Y88P"                                                              
----

[subs=attributes+]
++++
<div align="right">
<a href="{url-test}"><img src="{img-test}" alt="test"></a>
<a href="{url-publish}"><img src="{img-publish}" alt="publish"></a>
<a href="{url-hoc}"><img src="{img-hoc}" alt="hits of code"></a>
<a href="{url-releases}"><img src="{img-releases}" alt="release"></a>
<a href="{url-license}"><img src="{img-license}" alt="license"></a>
</div>
++++

toc::[]

ifdef::pages-build[]
++++
<div id="repo-link">
  <a href="https://github.com/rdavid/goredoer" aria-label="GitHub repository" target="_blank" rel="noopener">
    <svg viewBox="0 0 16 16" width="18" height="18" fill="currentColor" aria-hidden="true">
      <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8Z"/>
    </svg>
  </a>
</div>
++++
endif::[]

== About

The `goredoer` container image downloads, verifies, extracts, and builds
Sergey Matveev's {url-goredo}[`goredo`] utility.
`goredo` implements Daniel J. Bernstein's build system {url-redo}[`redo`]
in Go.
The publish workflow pushes the image to the GitHub Container Registry as
`ghcr.io/rdavid/goredoer`.

== Build

To build the image locally, start the Podman VM if needed and run:

[,sh]
----
git clone https://github.com/rdavid/goredoer.git &&
  cd ./goredoer &&
  podman build --file ./Containerfile --format docker .
----

== Usage

Copy the `goredo` binary from the image and let it create the `redo` command
symlinks.
Add these lines to your `Containerfile`:

[,sh]
----
COPY --from=ghcr.io/rdavid/goredoer:0.9.20260707 /goredo .
RUN goredo -symlinks
----

{url-shellbase}[`shellbase`] uses the `goredoer` image in its
{url-alpine}[`Containerfile`].

== Development

The project uses {url-redo}[`redo`] as its task runner.
Install {url-goredo}[`goredo`] to run the tasks:

* `redo build` builds the image from the {url-containerfile}[`Containerfile`].
* `redo lint` runs the following linters on the source files:
  {url-actionlint}[`actionlint`],
  {url-hadolint}[`hadolint`],
  {url-reuse}[`reuse`],
  {url-shellcheck}[`shellcheck`],
  {url-shfmt}[`shfmt`],
  {url-typos}[`typos`],
  {url-vale}[`vale`],
  {url-yamllint}[`yamllint`].
* `redo all` runs both `build` and `lint`.
* `redo clean` removes the build artifacts.

== License

{url-cv}[David Rabkin] holds the copyright and distributes `goredoer` under
the {url-license}[Zero-Clause BSD license].

ifdef::pages-build[]
++++
<footer id="site-footer">
  <div class="footer-left">
    <img src="favicon.svg" alt="" width="20" height="20">
    <span>goredoer by <a href="http://cv.rabkin.co.il" target="_blank" rel="noopener">David Rabkin</a></span>
  </div>
  <div class="footer-links">
    <a href="https://github.com/rdavid/goredoer" target="_blank" rel="noopener">GitHub</a>
    <a href="https://github.com/rdavid/goredoer/releases" target="_blank" rel="noopener">Releases</a>
    <a href="https://github.com/rdavid/goredoer/blob/master/LICENSES/0BSD.txt" target="_blank" rel="noopener">0BSD License</a>
  </div>
</footer>
++++
endif::[]
