// Settings:
:toc: macro
:!toc-title:

// URLs:
:url-alpine: https://github.com/rdavid/shellbase/blob/master/container/alpine/Containerfile
:url-containerfile: https://github.com/rdavid/goredoer/blob/master/Containerfile
:url-cv: http://cv.rabkin.co.il
:url-goredo: http://www.goredo.cypherpunks.ru/Install.html
:url-hadolint: https://github.com/hadolint/hadolint
:url-license: https://github.com/rdavid/goredoer/blob/master/LICENSE
:url-redo: http://cr.yp.to/redo.html
:url-shellbase: https://github.com/rdavid/shellbase
:url-shellcheck: https://github.com/koalaman/shellcheck
:url-shfmt: https://github.com/mvdan/sh
:url-typos: https://github.com/crate-ci/typos
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint

= Goredoer

image:https://github.com/rdavid/goredoer/actions/workflows/test.yml/badge.svg[test,link=https://github.com/rdavid/goredoer/actions/workflows/test.yml]
image:https://github.com/rdavid/goredoer/actions/workflows/publish.yml/badge.svg[publish,link=https://github.com/rdavid/goredoer/actions/workflows/publish.yml]
image:https://hitsofcode.com/github/rdavid/goredoer?branch=master&label=hits%20of%20code[hits of code,link=https://hitsofcode.com/view/github/rdavid/goredoer?branch=master]
image:https://img.shields.io/github/v/release/rdavid/goredoer?color=blue&label=%20&logo=semver&logoColor=white&style=flat[release),link=https://github.com/rdavid/goredoer/releases]
image:https://img.shields.io/github/license/rdavid/goredoer?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat[license,link=https://github.com/rdavid/goredoer/blob/master/LICENSE]

toc::[]

== About

The container image `goredoer` downloads, validates, extracts, and builds
Sergey Matveev's {url-goredo}[`goredo`] utility.
{url-goredo}[`goredo`] implements Daniel J. Bernstein's build system
{url-redo}[`redo`] in Go.

== Build

To build the image locally, start VM if needed `podman machine start`:

[,sh]
----
git clone git@github.com:rdavid/goredoer.git &&
  cd ./goredoer &&
  podman build --file ./Containerfile --format docker .
----

== Using

Include the following lines in your `Containerfile`:

[,sh]
----
COPY --from=ghcr.io/rdavid/goredoer:0.9.20240606 /goredo .
RUN goredo -symlinks
----

{url-shellbase}[`shellbase`] uses `goredoer` image in its
{url-alpine}[`Containerfile`].

== Test

The project uses Daniel J. Bernstein's build system {url-redo}[`redo`].
You can install Sergey Matveev's {url-goredo}[`goredo`] implementation.
`redo lint` applies the following linters to the source files:
{url-hadolint}[`hadolint`], {url-shellcheck}[`shellcheck`],
{url-shfmt}[`shfmt`], {url-typos}[`typos`], {url-vale}[`vale`],
{url-yamllint}[`yamllint`].
`redo build` builds the image from the {url-containerfile}[`Containerfile`].

== License

`goredoer` is copyright {url-cv}[David Rabkin] and available under a
{url-license}[Zero-Clause BSD license].
