// Settings:
:toc: macro
:!toc-title:

// URLs:
:img-hoc: https://hitsofcode.com/github/rdavid/goredoer?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/goredoer?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:img-publish: https://github.com/rdavid/goredoer/actions/workflows/publish.yml/badge.svg
:img-releases: https://img.shields.io/github/v/release/rdavid/goredoer?color=blue&label=%20&logo=semver&logoColor=white&style=flat
:img-test: https://github.com/rdavid/goredoer/actions/workflows/test.yml/badge.svg
:url-actionlint: https://github.com/rhysd/actionlint
:url-alpine: https://github.com/rdavid/shellbase/blob/master/container/alpine/Containerfile
:url-containerfile: https://github.com/rdavid/goredoer/blob/master/Containerfile
:url-cv: http://cv.rabkin.co.il
:url-goredo: http://www.goredo.cypherpunks.su/Install.html
:url-hadolint: https://github.com/hadolint/hadolint
:url-hoc: https://hitsofcode.com/view/github/rdavid/goredoer?branch=master
:url-license: https://github.com/rdavid/goredoer/blob/master/LICENSES/0BSD.txt
:url-publish: https://github.com/rdavid/goredoer/actions/workflows/publish.yml
:url-redo: http://cr.yp.to/redo.html
:url-releases: https://github.com/rdavid/goredoer/releases
:url-reuse: https://github.com/fsfe/reuse-action
:url-shellbase: https://github.com/rdavid/shellbase
:url-shellcheck: https://github.com/koalaman/shellcheck
:url-shfmt: https://github.com/mvdan/sh
:url-test: https://github.com/rdavid/goredoer/actions/workflows/test.yml
:url-typos: https://github.com/crate-ci/typos
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint

= Goredoer

image:{img-test}[test,link={url-test}]
image:{img-publish}[publish,link={url-publish}]
image:{img-hoc}[hits of code,link={url-hoc}]
image:{img-releases}[release),link={url-releases}]
image:{img-license}[license,link={url-license}]

toc::[]

== About

The container image `goredoer` downloads, validates, extracts, and builds
Sergey Matveev's {url-goredo}[`goredo`] utility.
{url-goredo}[`goredo`] implements Daniel J. Bernstein's build system
{url-redo}[`redo`] in Go.

== Build

To build the image locally, start VM if needed `podman machine start`:

[,sh]
----
git clone git@github.com:rdavid/goredoer.git &&
  cd ./goredoer &&
  podman build --file ./Containerfile --format docker .
----

== Using

Include the following lines in your `Containerfile`:

[,sh]
----
COPY --from=ghcr.io/rdavid/goredoer:0.9.20250808 /goredo .
RUN goredo -symlinks
----

{url-shellbase}[`shellbase`] uses `goredoer` image in its
{url-alpine}[`Containerfile`].

== Test

The project uses Daniel J. Bernstein's build system {url-redo}[`redo`].
You can install Sergey Matveev's {url-goredo}[`goredo`] implementation.
`redo lint` applies the following linters to the source files:
{url-actionlint}[`actionlint`],
{url-hadolint}[`hadolint`],
{url-reuse}[`reuse`],
{url-shellcheck}[`shellcheck`],
{url-shfmt}[`shfmt`],
{url-typos}[`typos`],
{url-vale}[`vale`],
{url-yamllint}[`yamllint`].
`redo build` builds the image from the {url-containerfile}[`Containerfile`].

== License

`goredoer` is copyright {url-cv}[David Rabkin] and available under a
{url-license}[Zero-Clause BSD license].
