# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: actionlint
'on':
  pull_request:
  push:
    branches: [master]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
env:
  VER: 1.7.12
jobs:
  actionlint:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - id: get
        env:
          URL: https://raw.githubusercontent.com/rhysd/actionlint/v${{ env.VER }}/scripts/download-actionlint.bash # yamllint disable-line
        run: bash <(curl --silent "$URL") "$VER"
      - run: ${{ steps.get.outputs.executable }}
