# SPDX-FileCopyrightText: 2023-2025 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: publish
'on':
  push:
    tags:
      - v*
env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io
jobs:
  publish:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            maintainer=David Rabkin
            org.opencontainers.image.description=Includes the Goredo utility
            org.opencontainers.image.licenses=0BSD
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.title=Goredoer
            org.opencontainers.image.vendor=David Rabkin
          tags: |
            type=raw,value=latest
            type=schedule,pattern=nightly
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}},priority=901
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Containerfile
          labels: ${{ steps.meta.outputs.labels }}
          platforms: "\
            linux/386,\
            linux/amd64,\
            linux/arm/v6,\
            linux/arm/v7,\
            linux/arm64,\
            linux/ppc64le,\
            linux/s390x"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
