# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
# The .do scripts are POSIX sh (`# shellcheck shell=sh`) but have no shebang,
# so shfmt defaults to its bash dialect and silently accepts bashisms. Pin
# `-ln posix` so shfmt parses them as sh and rejects bash-only constructs.
---
name: shfmt
'on':
  pull_request:
  push:
    branches: [master]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  shfmt:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - uses: mfinelli/setup-shfmt@v4.0.1
      - run: shfmt -ln posix -d ./*.do
