# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
# Without a shebang, shfmt parses the POSIX .do scripts in its default bash
# dialect and silently accepts bashisms. The -ln posix flag forces the sh
# dialect and makes shfmt reject bash-only constructs.
---
name: shfmt
'on':
  pull_request:
  push:
    branches: [master]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  shfmt:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - uses: mfinelli/setup-shfmt@v4.0.1
      - run: shfmt -ln posix -d ./*.do
